export enum InputType {
  TEXT = 'text',
  TIME = 'time',
  DATETIME = 'datetime-local',
  DATE = 'date',
  NUMBER = 'number',
  TEXTAREA = 'textarea',
  PASSWORD = 'password',
  CHECKBOX = 'checkbox',
  HIDDEN = 'hidden',
  SELECT = 'select',
  COLOR = 'color',
  EMAIL = 'email',
  MONTH = 'month',
  URL = 'url',
  PHONE = 'tel',
  SEARCH = 'search',
  RANGE = 'range',
  WEEK = 'week',
  FILE = 'file'
}