export enum InputType {
  INPUT_DATETIME = 'datetime-local',
  INPUT_DATE = 'date',
  INPUT_NUMBER = 'number',
  INPUT_TEXT = 'text',
  INPUT_TEXTAREA = 'textarea',
  INPUT_PASSWORD = 'password',
  INPUT_CHECKBOX = 'checkbox',
  INPUT_HIDDEN = 'hidden',
  SELECT = 'select',
  INPUT_COLOR = 'color',
  INPUT_EMAIL = 'email',
  INPUT_MONTH = 'month',
  INPUT_URL = 'url',
  INPUT_PHONE = 'tel',
  INPUT_SEARCH = 'search',
  INPUT_RANGE = 'range',
  INPUT_WEEK = 'week',
  INPUT_TIME = 'time',
  INPUT_FILE = 'file'
}